##
## EPITECH PROJECT, 2022
## Epitech-Template
## File description:
## workflow.yml
##

# The goal of this workflow is to merge the remote branch into the Epitech remote, but only if the tests pass.

name: "Push to remote"
on: push

jobs:
  test:
    name: Run tests before pushing to remote
    runs-on: "ubuntu-latest"
    container: "epitechcontent/epitest-docker:latest"

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
          fetch-depth: 0

      - name: Run push hooks
        run: "pip install websocket-client && python './.github/c_checker.py' --hard"

      - name: Check if it compiles
        shell: bash
        run: |
          make
          make clean
          make fclean
          make re
          ls myteams_cli myteams_server

      - name: Run tests
        run: "make tests_run"

      - name: Push to Epitech
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-NWP-400-LIL-4-1-myteams-quentin.desmettre.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
